import "./globals.css";
import "@radix-ui/themes/styles.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body>
      {/* Navbar is displayed at the top */}
      <Navbar />
      
      {/* Page content will render below the navbar */}
      <main className="mt-4">
        {children}
      </main>
      <Footer />
    </body>
  </html>
  );
}
